### your site title here

title: Chuck LePlant

description: > # this means to ignore newlines until "baseurl:"
    Sergio Basurco's personal portfolio. I'm a software developer based in Barcelona. Have fun browsing my little projects.
email: sergio.basurco@gmail.com
sass: 
    style: compressed

url: https://chuckleplant.github.io

owner:
    disqus-shortname: sergiobasurco
    name: Sergio Basurco
    email: sergio.basurco@gmail.com
    github: chuckleplant
    twitter: SergioBasurco
    linkedin: sergiobasurco

exclude:
- README.md

photo_dir:
- img/albums

include: 
- _pages

#Jekyll-Photo-Gallery Settings
exiftag:
 sources:
   - img/albums #Set to location of photos

destination: _deploy